### ISSUE TITLE
Set the Lock Collection Name

### ISSUE THREAD

**Issue by Steve-000** [rebus-org/Mongrow#1]
Hi Mogens Heller,

We are using your very light and easy to use migrator for one of our projects and it was exactly what I was looking for, so thank you for sharing this tool. 

When initializing the Migratior I found a small issue setting the Lock collection name.
In the constructor of Migrator when creating your DistributedLock object, you use _option.LockCollectionName as the LockId and for the name of the collection you always past the string "Locks". So the collectionName can not be customized.

Regards,

Steve

**Comment by mookid8000** [comment]
It's fixed in Mongrow 0.0.6, which is out on NuGet.org now 🙂 

Thanks for reporting it! 👍
